"""
generate.py — Seeded synthetic generator for Cascadia Deal Desk.

Cascadia Deal Desk · Part A

    ALL DATA IN THIS PROJECT IS SYNTHETIC. It is generated by this file from a
    fixed seed. There is no real company, customer, part number, price, or
    person anywhere in it, and there never will be. Every figure the site
    displays traces back to the parameter block below.

Output: data/raw/dim_customer.csv        data/raw/fact_quote_line.csv
        data/raw/dim_product.csv         data/raw/fact_booking.csv
        data/raw/dim_rep.csv             data/raw/fact_standard_cost.csv
        data/raw/dim_date.csv            data/raw/generator_manifest.json
        data/raw/dim_agreement.csv       governance/generator_assumptions.md

WHY THIS FILE IS SHAPED THE WAY IT IS
-------------------------------------
The easy way to build a pricing dataset is to draw the quoted price from a
distribution centred on the agreed price. That produces a cloud of small,
directionless variances — an exception table with no story in it, and a
threshold control that does nothing interesting when you drag it.

So variance here is not drawn. It is GENERATED FROM A MECHANISM:

    Every customer/product relationship carries a prior_price — what that
    customer paid before the current agreement. When an agreement is signed,
    the agreed_price sits at a PREMIUM above prior_price. An off-agreement
    line is a rep quoting the PRIOR price: the old number, pulled from habit
    or from a stale spreadsheet.

That single mechanism gives the analysis every property it needs for free.
The variance is negative, because the premium was positive. It is larger
where the premium was larger, because it IS the premium. And it is
explainable, because the counterfactual is a real number sitting in the data.

Jitter exists on top of that (a rounded number, a slightly stale sheet), but
it is deliberately second-order. It is never the driver.

Usage:
    python src/generate.py
"""

import json
import math
import random
from datetime import date, timedelta
from pathlib import Path

import pandas as pd

# The matching rule lives in the analytics layer and is imported here, so the
# generator prices each quote against exactly the rule conform.py will later
# apply. One rule, one implementation, no drift between them.
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from conform import TOLERANCE_PCT, resolve_agreement

REPO_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = REPO_ROOT / "data" / "raw"
ASSUMPTIONS_PATH = REPO_ROOT / "governance" / "generator_assumptions.md"

# ===========================================================================
# PARAMETER BLOCK — every tunable assumption in this dataset, in one place.
# ===========================================================================

SEED = 20260801                     # fixed seed; same seed => byte-identical CSVs
AS_OF = date(2026, 8, 1)            # the "today" the register's status column describes
WINDOW_START = date(2024, 8, 1)     # first quote date
WINDOW_END = date(2026, 7, 31)      # last quote date (24 months of activity)

N_CUSTOMERS = 40                    # accounts in the book
N_PRODUCTS = 120                    # sellable parts
N_REPS = 12                         # sales reps carrying a quota
TARGET_QUOTE_LINES = 3000           # approximate; quotes are 1-4 lines so we land near it

# --- product families -------------------------------------------------------
# Six families, each with a base unit price. Parts vary +/-12% around the base,
# which is what makes a FAMILY-scope agreement at a single negotiated unit price
# a sensible commercial instrument rather than an absurdity.
FAMILIES = {
    "Vertical Probe Heads":   dict(prefix="VPH", base_price=34_000, qty=(1, 8)),
    "Cantilever Probe Cards": dict(prefix="CPC", base_price=11_500, qty=(2, 24)),
    "Burn-In Sockets":        dict(prefix="BIS", base_price=420,    qty=(50, 800)),
    "Load Boards":            dict(prefix="LDB", base_price=7_800,  qty=(2, 20)),
    "Thermal Control Units":  dict(prefix="TCU", base_price=46_000, qty=(1, 4)),
    "Calibration Standards":  dict(prefix="CAL", base_price=2_100,  qty=(4, 40)),
}
PART_PRICE_SPREAD = 0.12            # part price varies +/-12% around its family base

N_LATE_LAUNCH_PRODUCTS = 8          # parts that launch DURING the window (coverage gaps)

# --- the premium: what negotiation actually won ----------------------------
PREMIUM_NORMAL = (0.03, 0.15)       # usual renegotiation uplift over prior_price
PREMIUM_HARD = (0.15, 0.30)         # a hard renegotiation
PREMIUM_HARD_SHARE = 0.20           # share of agreements negotiated hard
RENEWAL_PREMIUM_NORMAL = (0.025, 0.12)   # second/third round: less room left
RENEWAL_PREMIUM_HARD = (0.12, 0.22)

# --- how a quote gets priced ------------------------------------------------
ON_AGREEMENT_JITTER = 0.0038        # +/- rounding noise; stays INSIDE TOLERANCE_PCT
OFF_AGREEMENT_JITTER = 0.004        # stale-sheet noise on top of the prior price
ROUND_TO_NICE_NUMBER_P = 0.22       # chance a rep rounds the quote to a tidy figure

# --- concentration: three multiplicative drivers of going off-agreement -----
BASE_OFF_AGREEMENT_RATE = 0.044     # baseline probability before any driver applies
REP_LEAK_STANDOUT = 4.0             # the one rep who is the story
REP_LEAK_HIGH = (1.9, 2.4)          # three more undisciplined reps
REP_LEAK_LOW = (0.30, 0.55)         # the disciplined eight
N_LEAKY_REPS = 4                    # of 12 — these carry the clear majority

RECENCY_PEAK_BOOST = 3.0            # multiplier at day 0 of a new agreement
RECENCY_DECAY_DAYS = 45.0           # exponential decay constant; ~1.8x still at day 60
                                    # This is the real failure mode: the sheet
                                    # has not caught up with the new agreement yet.

CUSTOMER_LEAK_SPREAD = (0.25, 2.6)  # per-account multiplier
N_HOT_CUSTOMERS = 6                 # accounts that carry most of the exposure
CUSTOMER_LEAK_HOT = (3.0, 4.6)
PRODUCT_LEAK_SPREAD = (0.5, 1.8)    # per-part multiplier
P_OFF_CLAMP = (0.004, 0.85)         # keep the product of the drivers sane

# --- coverage: agreements, chains, and the gaps between them ---------------
# A chain TILES the window rather than sitting somewhere inside it: a customer
# under agreement normally stays under agreement, renewing. Coverage gaps are
# created deliberately and sparingly, because a register where a third of the
# book has silently fallen out of coverage is not credible.
N_NEVER_SIGN_CUSTOMERS = 1          # accounts with no agreement at all
P_PAIR_COVERED = 0.99               # of a signing customer's parts, share under agreement
CHAIN_LENGTH_WEIGHTS = {1: 0.70, 2: 0.22, 3: 0.08}   # ~30% of pairs renew at least once
SUCCESSOR_CLEAN_P = 0.55            # successor starts the day after predecessor ends
SUCCESSOR_OVERLAP_P = 0.30          # successor back-dated 14-42 days INTO predecessor
SUCCESSOR_OVERLAP_DAYS = (14, 42)   # -> forces the supersession test to be time-aware
SUCCESSOR_GAP_DAYS = (30, 120)      # the remaining 15%: a mid-chain lapse
P_CHAIN_LAPSES_AT_END = 0.12        # chain simply not renewed -> agreement_lapsed
CHAIN_BACKDATE_DAYS = (0, 180)      # first link starts before the window opens
CHAIN_TAIL_DAYS = (30, 400)         # last link extends past the window (still in force)
CHAIN_LAPSE_TAIL_DAYS = (20, 240)   # ...or ends this far before the window closes

N_FAMILY_SCOPE_CUSTOMERS = 14       # accounts holding a family-wide agreement
P_PART_OVERRIDE_ON_FAMILY = 0.55    # of those, share that ALSO hold part-scope overrides
N_UNLINKED_OVERLAPS = 9             # duplicate registrations with no supersession link
                                    # -> the case the RECENCY tiebreak exists for

# --- legitimate, documented deviations -------------------------------------
EXCEPTION_BASE_RATE = 0.013         # per covered line, before account weighting
N_EXCEPTION_ACCOUNTS = 3            # strategic accounts where exceptions cluster
EXCEPTION_ACCOUNT_BOOST = 9.0
EXCEPTION_OTHER_DAMPEN = 0.35
P_EXCEPTION_POSITIVE = 0.35         # priced ABOVE agreement — "exception" != "loss"
EXCEPTION_MAGNITUDE = (0.015, 0.09)
EXCEPTION_REASON_CODES = [
    "volume_ramp_concession",
    "competitive_displacement",
    "qualification_pricing",
    "end_of_life_clearance",
]

# --- standard cost moves underneath the agreement --------------------------
COST_RATIO_AT_START = (0.52, 0.68)  # standard cost as a share of list price
COST_DRIFT_DOWN = (-0.08, -0.02)    # yield learning
COST_DRIFT_FLAT = (-0.015, 0.015)
COST_DRIFT_UP = (0.02, 0.08)        # materials inflation
COST_DRIFT_MIX = (0.45, 0.35, 0.20) # down / flat / up
N_MARGIN_EROSION_CUSTOMERS = 4      # accounts deliberately built to show the SECOND
                                    # finding: perfect compliance, eroding margin,
                                    # because cost moved under a locked price.

# --- bookings: what actually converted -------------------------------------
CONVERSION_BY_SEGMENT = {"Strategic": 0.66, "Core": 0.60, "Emerging": 0.52}
BOOKING_LAG_DAYS = (5, 70)          # quote -> order. Capital equipment sits a while.
P_BOOKED_PRICE_DIFFERS = 0.05       # price moved between quote and order
BOOKED_PRICE_DRIFT = 0.010
P_PARTIAL_QUANTITY = 0.30           # partial orders are normal
PARTIAL_QUANTITY_RANGE = (0.55, 0.95)
LOSS_DECISION_LAG_DAYS = (20, 240)  # how long a losing quote sits before it dies.
                                    # A line whose decision date falls beyond the
                                    # window is still OPEN — undecided, and
                                    # therefore still fixable. That is the whole
                                    # point of separating open from realized.

# --- volume shape -----------------------------------------------------------
YOY_GROWTH = 0.175                  # year-2 quote volume vs year-1
QUARTER_WEIGHTS = {1: 0.95, 2: 1.00, 3: 0.97, 4: 1.15}   # mild Q4 push
LINES_PER_QUOTE_WEIGHTS = {1: 0.46, 2: 0.28, 3: 0.17, 4: 0.09}

# --- invented names. Plausibly industrial, obviously fictional. -------------
# Deliberately Pacific-Northwest flavoured to match the Cascadia portfolio and
# to stay clear of resembling any real semiconductor firm.
CUSTOMER_NAMES = [
    "Alderwood Microsystems", "Basalt Semiconductor Works", "Cedarline Devices",
    "Driftwood Integrated", "Elkhorn Test Systems", "Fernvale Microelectronics",
    "Glacier Peak Devices", "Harborlight Semiconductors", "Ironwood Wafer Labs",
    "Juniper Ridge Micro", "Kettle Falls Instruments", "Larchmont Silicon",
    "Madrona Test Group", "Nootka Devices", "Olympic Foundry Partners",
    "Pemberton Microdevices", "Quilcene Systems", "Rainshadow Electronics",
    "Saltspring Semiconductor", "Tamarack Micro Labs", "Umatilla Devices",
    "Vashon Integrated Circuits", "Wallowa Test Solutions", "Yarrow Point Micro",
    "Zircon Bay Devices", "Ashfall Microsystems", "Beacon Rock Silicon",
    "Chinook Device Labs", "Deception Pass Micro", "Emerald Ridge Electronics",
    "Foxglove Semiconductor", "Granite Falls Devices", "Hoodsport Instruments",
    "Inlet Point Micro", "Kingfisher Test Labs", "Lupine Valley Devices",
    "Mosswood Semiconductor", "Newhalem Microsystems", "Orcas Device Works",
    "Puffin Cove Electronics",
]
REP_NAMES = [
    "Dana Whitfield", "Marcus Ellery", "Priya Raghavan", "Tomas Lindqvist",
    "Alicia Moreno", "Kenji Watanabe", "Rachel Okonkwo", "Devin Marsh",
    "Simone Bellini", "Grant Feldman", "Yara Haddad", "Colin Brasher",
]
TERRITORIES = ["West", "Central", "East", "International"]
SEGMENTS = ["Strategic", "Core", "Emerging"]
REGIONS = ["Americas", "EMEA", "APAC", "Japan"]

DISCLOSURE = "Synthetic data, seeded generator. Simulated — not real company data."


# ===========================================================================
# Small helpers
# ===========================================================================

def month_starts(start: date, end: date) -> list:
    """Every month-start between two dates, inclusive of the starting month."""
    out, cur = [], date(start.year, start.month, 1)
    while cur <= end:
        out.append(cur)
        cur = date(cur.year + (cur.month == 12), (cur.month % 12) + 1, 1)
    return out


def add_months(d: date, n: int) -> date:
    """Add n months, clamping the day so 31 Jan + 1 month lands on 28/29 Feb."""
    total = (d.year * 12 + d.month - 1) + n
    y, m = divmod(total, 12)
    m += 1
    last = (date(y + (m == 12), (m % 12) + 1, 1) - timedelta(days=1)).day
    return date(y, m, min(d.day, last))


def nice_round(price: float) -> float:
    """A rep typing a tidy number instead of the exact one. Second-order noise."""
    step = 5 if price < 1_000 else 50 if price < 20_000 else 100
    return float(round(price / step) * step)


def pick_weighted(rng: random.Random, weights: dict):
    """Choose a key from {key: weight}."""
    keys = list(weights)
    return rng.choices(keys, weights=[weights[k] for k in keys], k=1)[0]


# ===========================================================================
# Dimension builders
# ===========================================================================

def build_reps(rng: random.Random) -> list:
    """12 reps. Four of them — one especially — will carry most of the leakage.

    Rep discipline is the first of the three concentration drivers. It is what
    makes the "by rep" ranked bar on the exception page have a head and a tail
    instead of twelve equal bars, and it is what turns the finding into a
    coaching conversation rather than a system complaint.
    """
    reps = []
    leaky = set(rng.sample(range(N_REPS), N_LEAKY_REPS))
    standout = rng.choice(sorted(leaky))
    for i, name in enumerate(REP_NAMES):
        if i == standout:
            leak = REP_LEAK_STANDOUT
        elif i in leaky:
            leak = rng.uniform(*REP_LEAK_HIGH)
        else:
            leak = rng.uniform(*REP_LEAK_LOW)
        reps.append({"rep_id": f"R{i + 1:02d}", "name": name,
                     "territory": TERRITORIES[i % len(TERRITORIES)],
                     "_leak_factor": round(leak, 3)})
    return reps


def build_products(rng: random.Random) -> list:
    """120 parts across 6 families, with launch dates and a cost trajectory.

    N_LATE_LAUNCH_PRODUCTS of them launch DURING the analysis window. Those are
    what create genuine `product_launched_after_agreement` coverage gaps: the
    part did not exist when the customer's agreement was negotiated.
    """
    products, per_family = [], N_PRODUCTS // len(FAMILIES)
    late_launch_slots = set(rng.sample(range(N_PRODUCTS), N_LATE_LAUNCH_PRODUCTS))
    idx = 0
    for family, spec in FAMILIES.items():
        for n in range(per_family):
            if idx in late_launch_slots:
                # Launches inside the window -> post-dates existing agreements.
                launch = WINDOW_START + timedelta(days=rng.randint(45, 560))
            else:
                launch = WINDOW_START - timedelta(days=rng.randint(200, 2200))
            list_price = round(spec["base_price"]
                               * rng.uniform(1 - PART_PRICE_SPREAD, 1 + PART_PRICE_SPREAD), 2)
            trend = rng.choices(["down", "flat", "up"], weights=COST_DRIFT_MIX, k=1)[0]
            drift = rng.uniform(*{"down": COST_DRIFT_DOWN, "flat": COST_DRIFT_FLAT,
                                  "up": COST_DRIFT_UP}[trend])
            products.append({
                "product_id": f"P{idx + 1:04d}",
                "part_number": f"{spec['prefix']}-{1000 + (idx * 37) % 8999}",
                "family": family, "launch_date": launch.isoformat(),
                "_list_price": list_price, "_qty_range": spec["qty"],
                "_cost_trend": trend, "_cost_drift": round(drift, 4),
                "_leak_factor": round(rng.uniform(*PRODUCT_LEAK_SPREAD), 3),
            })
            idx += 1
    return products


def build_customers(rng: random.Random, products: list) -> list:
    """40 accounts, each with a basket of parts and a leakage propensity.

    Two groups are planted on purpose and both are declared in the assumptions
    doc, because a reader is entitled to know which findings were designed in:

      * N_HOT_CUSTOMERS  — accounts that carry most of the dollar exposure, so
        the ranked-by-dollars chart has a genuine head.
      * N_MARGIN_EROSION_CUSTOMERS — accounts with near-perfect compliance whose
        parts have RISING standard cost. These produce the second, separate
        finding: the agreement was honoured and the margin still fell.
    """
    up_cost_pool = [p for p in products if p["_cost_trend"] == "up"]
    hot = set(rng.sample(range(N_CUSTOMERS), N_HOT_CUSTOMERS))
    # Erosion accounts are chosen from OUTSIDE the hot set — the whole point is
    # that they look clean on the leakage page.
    erosion = set(rng.sample(sorted(set(range(N_CUSTOMERS)) - hot),
                             N_MARGIN_EROSION_CUSTOMERS))
    exception_accounts = set(rng.sample(sorted(set(range(N_CUSTOMERS)) - erosion),
                                        N_EXCEPTION_ACCOUNTS))
    # Accounts that never signed anything at all — one cause of
    # `never_under_agreement`. Drawn from outside the hot/planted sets so a
    # high-volume account does not single-handedly flood the no-agreement bucket.
    never_sign = set(rng.sample(
        sorted(set(range(N_CUSTOMERS)) - hot - erosion - exception_accounts),
        N_NEVER_SIGN_CUSTOMERS))

    customers = []
    for i, name in enumerate(CUSTOMER_NAMES):
        if i in erosion:
            leak = 0.12                                   # disciplined by design
            basket_pool = up_cost_pool
            basket_size = rng.randint(6, 11)
        elif i in hot:
            leak = rng.uniform(*CUSTOMER_LEAK_HOT)
            basket_pool = products
            basket_size = rng.randint(9, 16)
        else:
            leak = rng.uniform(*CUSTOMER_LEAK_SPREAD)
            basket_pool = products
            basket_size = rng.randint(5, 14)

        # A basket is drawn from 2-3 families so families mean something.
        fams = rng.sample(sorted(FAMILIES), rng.randint(2, 3))
        candidates = [p for p in basket_pool if p["family"] in fams] or basket_pool
        basket = rng.sample(candidates, min(basket_size, len(candidates)))

        customers.append({
            "customer_id": f"C{i + 1:03d}", "name": name,
            "segment": ("Strategic" if i in hot | exception_accounts
                        else rng.choices(SEGMENTS, weights=[0.2, 0.5, 0.3], k=1)[0]),
            "region": rng.choice(REGIONS),
            "_leak_factor": round(leak, 3),
            "_price_factor": round(rng.uniform(0.82, 1.05), 4),   # negotiating power
            "_basket": [p["product_id"] for p in basket],
            "_never_signs": i in never_sign,
            "_is_exception_account": i in exception_accounts,
            "_is_erosion_account": i in erosion,
        })
    return customers


def build_dates() -> list:
    """A plain daily calendar over the analysis window."""
    out, cur = [], WINDOW_START
    while cur <= WINDOW_END:
        out.append({"date_key": int(cur.strftime("%Y%m%d")), "date": cur.isoformat(),
                    "year": cur.year, "quarter": f"Q{(cur.month - 1) // 3 + 1}",
                    "month": cur.month, "month_name": cur.strftime("%B")})
        cur += timedelta(days=1)
    return out


def build_standard_costs(rng: random.Random, products: list) -> list:
    """Quarterly cost steps per part, spanning the whole window with no gaps.

    Cost is NOT decoration. A locked price plus a rising cost is a different
    failure from a rep quoting the wrong number, and the customer page has to
    be able to tell the two apart. The first segment starts before the window
    so every quote date is covered by exactly one segment.
    """
    rows = []
    starts = [date(2024, 1, 1)]
    while starts[-1] < WINDOW_END:
        starts.append(add_months(starts[-1], 3))
    for p in products:
        cost = p["_list_price"] * rng.uniform(*COST_RATIO_AT_START)
        for i, s in enumerate(starts):
            end = (starts[i + 1] - timedelta(days=1)) if i + 1 < len(starts) \
                else date(2099, 12, 31)
            rows.append({"product_id": p["product_id"],
                         "effective_start": s.isoformat(),
                         "effective_end": end.isoformat(),
                         "standard_cost": round(cost, 2)})
            # One quarter of the annual drift, plus a little quarter-to-quarter noise.
            cost *= (1 + p["_cost_drift"] / 4 + rng.gauss(0, 0.004))
    return rows


# ===========================================================================
# The agreement register — the thing that should have been a dataset all along
# ===========================================================================

def draw_premium(rng: random.Random, is_renewal: bool) -> float:
    """How much the negotiation actually won over the previous price."""
    hard = rng.random() < PREMIUM_HARD_SHARE
    if is_renewal:
        lo, hi = RENEWAL_PREMIUM_HARD if hard else RENEWAL_PREMIUM_NORMAL
    else:
        lo, hi = PREMIUM_HARD if hard else PREMIUM_NORMAL
    return rng.uniform(lo, hi)


def build_agreements(rng: random.Random, customers: list, products: list) -> list:
    """The governed register: chains, overlaps, scope conflicts, and lapses.

    Four structures are built here on purpose, because each one is a case the
    matching rule has to survive and therefore a case matching_rules.md has to
    document with a worked example:

      chains       — 2-3 agreements over the 24 months, each superseding the last
      overlaps     — a successor back-dated INTO its predecessor's window, which
                     is what forces the supersession test to be time-aware
      family scope — a family-wide agreement that a part-scope agreement
                     overrides for specific parts (the specificity tiebreak)
      lapses       — agreements that run out with no successor, so a naive join
                     on customer + product alone would still pick them up
    """
    by_id = {}
    agreements = []
    seq = [0]

    def new_id():
        seq[0] += 1
        return f"A{seq[0]:04d}"

    def emit(customer, scope, product, family, prior_price, start, end, is_renewal):
        premium = draw_premium(rng, is_renewal)
        agreed = round(prior_price * (1 + premium), 2)
        # Committed capacity, in units, sized to the part's typical order size.
        typical_qty = product["_qty_range"] if product else (5, 40)
        committed = int(rng.randint(*typical_qty) * rng.randint(8, 30))
        row = {
            "agreement_id": new_id(), "customer_id": customer["customer_id"],
            "scope": scope,
            "product_id": product["product_id"] if scope == "part" else None,
            "family": family if scope == "family" else None,
            "agreed_price": agreed,
            "effective_start": start.isoformat(), "effective_end": end.isoformat(),
            "committed_units": committed,
            "approval_ref": f"PA-{start.year}-{seq[0]:04d}",
            "status": None,                     # stamped at the end, as of AS_OF
            "superseded_by": None,
            "prior_price": round(prior_price, 2),
            "premium_pct": round(premium, 4),
        }
        agreements.append(row)
        by_id[row["agreement_id"]] = row
        return row

    def build_chain(customer, scope, product, family, base_price):
        """One customer/scope relationship across the window, as 1-3 links.

        The chain TILES the analysis window: it starts before the window opens
        and normally runs past the far end, with the links being renewals. That
        is how a real book behaves — a customer under agreement stays under
        agreement. Gaps are then introduced deliberately and sparingly, in two
        distinct flavours, because each one is a different business failure:

          mid-chain gap  (SUCCESSOR_GAP_DAYS)   — renewal was late
          tail lapse     (P_CHAIN_LAPSES_AT_END) — renewal never happened

        Both surface as `agreement_lapsed`. Getting this wrong in the other
        direction — chains sitting somewhere inside the window — leaves months
        of trailing "lapsed" coverage behind every agreement and floods the
        no-agreement bucket with noise.
        """
        n_links = pick_weighted(rng, CHAIN_LENGTH_WEIGHTS)
        start = WINDOW_START - timedelta(days=rng.randint(*CHAIN_BACKDATE_DAYS))
        if rng.random() < P_CHAIN_LAPSES_AT_END:
            horizon = WINDOW_END - timedelta(days=rng.randint(*CHAIN_LAPSE_TAIL_DAYS))
        else:
            horizon = WINDOW_END + timedelta(days=rng.randint(*CHAIN_TAIL_DAYS))
        span = (horizon - start).days

        # Interior renewal boundaries, evenly spaced across the span with jitter.
        fracs = sorted(rng.uniform(i / n_links - 0.08, i / n_links + 0.08)
                       for i in range(1, n_links))
        boundaries = [start + timedelta(days=int(span * f)) for f in fracs] + [horizon]

        prior, links, cur_start = base_price, [], start
        for i, boundary in enumerate(boundaries):
            row = emit(customer, scope, product, family, prior, cur_start, boundary, i > 0)
            links.append(row)
            if i == len(boundaries) - 1:
                break
            # Where does the successor start relative to this one's end?
            roll = rng.random()
            if roll < SUCCESSOR_CLEAN_P:
                nxt = boundary + timedelta(days=1)                  # clean handover
            elif roll < SUCCESSOR_CLEAN_P + SUCCESSOR_OVERLAP_P:
                nxt = boundary - timedelta(days=rng.randint(*SUCCESSOR_OVERLAP_DAYS))
            else:
                nxt = boundary + timedelta(days=rng.randint(*SUCCESSOR_GAP_DAYS))
            # A renewal is negotiated up from the price it replaces.
            prior, cur_start = row["agreed_price"], nxt
        # Link the chain: every predecessor points at its successor.
        for a, b in zip(links, links[1:]):
            a["superseded_by"] = b["agreement_id"]
        return links

    products_by_id = {p["product_id"]: p for p in products}
    signing = [c for c in customers if not c["_never_signs"]]
    family_scope_customers = set(
        rng.sample([c["customer_id"] for c in signing],
                   min(N_FAMILY_SCOPE_CUSTOMERS, len(signing))))

    for c in signing:
        basket = [products_by_id[pid] for pid in c["_basket"]]
        fams = sorted({p["family"] for p in basket})

        # --- family-scope agreements -------------------------------------
        family_covered = set()
        if c["customer_id"] in family_scope_customers:
            fam = rng.choice(fams)
            family_covered.add(fam)
            base = FAMILIES[fam]["base_price"] * c["_price_factor"]
            build_chain(c, "family", None, fam, base)

        # --- part-scope agreements ---------------------------------------
        for p in basket:
            # A part already covered by a family agreement only gets its own
            # part-scope agreement some of the time — that is the override case.
            if p["family"] in family_covered:
                if rng.random() > P_PART_OVERRIDE_ON_FAMILY:
                    continue
            elif rng.random() > P_PAIR_COVERED:
                continue          # deliberately uncovered -> never_under_agreement
            # A part that launched after the window opened cannot have been in
            # an agreement signed before it existed.
            if date.fromisoformat(p["launch_date"]) > WINDOW_START:
                continue
            build_chain(c, "part", p, p["family"], p["_list_price"] * c["_price_factor"])

    # --- register-hygiene defects: duplicate registrations, no supersession --
    # Two agreements of equal specificity covering the same part and the same
    # dates, with NOTHING linking them. This is the case the RECENCY tiebreak
    # exists for, and it is a real thing that happens when two people paper the
    # same deal. Effective starts are deliberately different so the tiebreak
    # resolves; an identical start would be an unresolvable tie and would
    # (correctly) fail the run.
    part_agreements = [a for a in agreements if a["scope"] == "part"
                       and a["superseded_by"] is None]
    for src in rng.sample(part_agreements, min(N_UNLINKED_OVERLAPS, len(part_agreements))):
        customer = next(c for c in customers if c["customer_id"] == src["customer_id"])
        product = products_by_id[src["product_id"]]
        start = date.fromisoformat(src["effective_start"]) + timedelta(days=rng.randint(20, 90))
        end = date.fromisoformat(src["effective_end"]) + timedelta(days=rng.randint(5, 60))
        if start >= end:
            continue
        emit(customer, "part", product, product["family"],
             src["prior_price"] * rng.uniform(0.98, 1.03), start, end, True)

    # --- stamp status AS OF the as-of date ---------------------------------
    # This column describes the register TODAY, which is what the agreement
    # timeline on the customer page renders. The MATCHER does not read it: it
    # asks the same two questions as of the QUOTE date instead. Both meanings
    # are spelled out in governance/matching_rules.md.
    for a in agreements:
        successor = by_id.get(a["superseded_by"]) if a["superseded_by"] else None
        if successor and date.fromisoformat(successor["effective_start"]) <= AS_OF:
            a["status"] = "superseded"
        elif date.fromisoformat(a["effective_end"]) < AS_OF:
            a["status"] = "expired"
        else:
            a["status"] = "active"
    return agreements


# ===========================================================================
# Quotes — where the mechanism produces the variance
# ===========================================================================

def monthly_line_targets(rng: random.Random) -> dict:
    """Allocate the target line count across 24 months with growth + a Q4 push."""
    months = month_starts(WINDOW_START, WINDOW_END)
    weights = {}
    for m in months:
        w = QUARTER_WEIGHTS[(m.month - 1) // 3 + 1]
        if m >= add_months(WINDOW_START, 12):
            w *= (1 + YOY_GROWTH)
        weights[m] = w
    total_w = sum(weights.values())
    return {m: max(1, round(TARGET_QUOTE_LINES * w / total_w)) for m, w in weights.items()}


def off_agreement_probability(customer, rep, product, agreement, quote_date) -> float:
    """P(this line is quoted off the agreement) — a product of three drivers.

    All three are recoverable from the finished dataset, which is the point:
    the analysis should be able to say WHO, WHEN and WHERE, not just HOW MUCH.

      rep      — discipline varies, and four reps carry the majority
      recency  — probability peaks in the days right after a renegotiation and
                 decays. The stale sheet has not caught up yet.
      account  — a handful of accounts and parts carry most of the exposure
    """
    days_since = (quote_date - date.fromisoformat(agreement["effective_start"])).days
    recency = 1 + RECENCY_PEAK_BOOST * math.exp(-max(days_since, 0) / RECENCY_DECAY_DAYS)
    p = (BASE_OFF_AGREEMENT_RATE * rep["_leak_factor"] * recency
         * customer["_leak_factor"] * product["_leak_factor"])
    return min(max(p, P_OFF_CLAMP[0]), P_OFF_CLAMP[1])


def build_quotes(rng: random.Random, customers: list, products: list,
                 reps: list, agreements: list) -> tuple:
    """Generate quote lines, price them, and convert some of them to bookings."""
    products_by_id = {p["product_id"]: p for p in products}
    agreements_by_customer: dict = {}
    for a in agreements:
        agreements_by_customer.setdefault(a["customer_id"], []).append(a)
    agreement_by_id = {a["agreement_id"]: a for a in agreements}

    # Each account has a primary rep; occasionally someone else covers.
    primary_rep = {c["customer_id"]: reps[i % len(reps)] for i, c in enumerate(customers)}
    # Weight account activity so quote volume itself is concentrated.
    activity = {c["customer_id"]: rng.uniform(0.5, 1.0) * (2.4 if c["_leak_factor"] > 2.5 else 1.0)
                for c in customers}

    lines, bookings = [], []
    quote_seq, booking_seq = [0], [0]
    exception_seq = [0]

    for month, target in monthly_line_targets(rng).items():
        emitted = 0
        while emitted < target:
            customer = rng.choices(customers,
                                   weights=[activity[c["customer_id"]] for c in customers],
                                   k=1)[0]
            if not customer["_basket"]:
                continue
            rep = primary_rep[customer["customer_id"]] if rng.random() < 0.85 \
                else rng.choice(reps)
            last_day = (add_months(month, 1) - timedelta(days=1))
            quote_date = month + timedelta(days=rng.randint(0, (last_day - month).days))
            if not (WINDOW_START <= quote_date <= WINDOW_END):
                continue

            quote_seq[0] += 1
            quote_id = f"Q-{quote_date.year}-{quote_seq[0]:06d}"
            n_lines = min(pick_weighted(rng, LINES_PER_QUOTE_WEIGHTS),
                          len(customer["_basket"]), target - emitted or 1)
            for line_no, pid in enumerate(rng.sample(customer["_basket"], n_lines), start=1):
                product = products_by_id[pid]
                # A part cannot be quoted before it launches.
                if date.fromisoformat(product["launch_date"]) > quote_date:
                    continue
                line = price_line(rng, customer, product, rep, quote_date, quote_id,
                                  line_no, agreements_by_customer.get(customer["customer_id"], []),
                                  agreement_by_id, exception_seq)
                lines.append(line)
                emitted += 1
                book = maybe_book(rng, line, customer, booking_seq)
                if book:
                    bookings.append(book)
    return lines, bookings


def price_line(rng, customer, product, rep, quote_date, quote_id, line_no,
               customer_agreements, agreement_by_id, exception_seq) -> dict:
    """Decide what number the rep typed. This is where the mechanism lives."""
    winner, _ = resolve_agreement(customer_agreements, product["product_id"],
                                  product["family"], quote_date, agreement_by_id)
    qty = rng.randint(*product["_qty_range"])
    approval_ref = reason_code = None

    if winner is None:
        # No agreement governs, so there is no premium to lose and no variance
        # to measure. The line is priced at the going rate for that account.
        price = product["_list_price"] * customer["_price_factor"] * (1 + rng.gauss(0, 0.02))
        stage = None
    else:
        agreed, prior = winner["agreed_price"], winner["prior_price"]
        p_exception = (EXCEPTION_BASE_RATE
                       * (EXCEPTION_ACCOUNT_BOOST if customer["_is_exception_account"]
                          else EXCEPTION_OTHER_DAMPEN))
        if rng.random() < p_exception:
            # A DOCUMENTED, APPROVED deviation. These are the legitimate
            # exceptions that make threshold calibration a real exercise
            # instead of theatre — and some of them are priced ABOVE the
            # agreement, because "exception" does not mean "loss".
            magnitude = rng.uniform(*EXCEPTION_MAGNITUDE)
            sign = 1 if rng.random() < P_EXCEPTION_POSITIVE else -1
            price = agreed * (1 + sign * magnitude)
            exception_seq[0] += 1
            approval_ref = f"DR-{quote_date.year}-{exception_seq[0]:04d}"
            reason_code = rng.choice(EXCEPTION_REASON_CODES)
        elif rng.random() < off_agreement_probability(customer, rep, product,
                                                      winner, quote_date):
            # THE MECHANISM: the rep quotes the PRIOR price. Not a random
            # perturbation of the agreed price — the previous number, pulled
            # from habit or from a spreadsheet that has not caught up.
            price = prior * (1 + rng.gauss(0, OFF_AGREEMENT_JITTER))
            if rng.random() < ROUND_TO_NICE_NUMBER_P:
                price = nice_round(price)
        else:
            # Priced to the agreement, give or take rounding.
            price = agreed * (1 + rng.uniform(-ON_AGREEMENT_JITTER, ON_AGREEMENT_JITTER))
        stage = None

    price = round(price, 2)
    # Safety rail: a line INTENDED as on-agreement must land inside the
    # tolerance band after rounding, and an intended deviation must land
    # outside it. Without this a nice-round could accidentally flip a line's
    # match_status and quietly corrupt the target mix.
    if winner is not None:
        agreed = winner["agreed_price"]
        intended_on = abs(price - agreed) <= TOLERANCE_PCT * agreed
        actually_on = abs(round(price, 2) - agreed) <= TOLERANCE_PCT * agreed
        if intended_on != actually_on:                      # pragma: no cover
            price = round(agreed * (1 + rng.uniform(-ON_AGREEMENT_JITTER,
                                                    ON_AGREEMENT_JITTER)), 2)

    return {"quote_id": quote_id, "line_no": line_no,
            "customer_id": customer["customer_id"], "product_id": product["product_id"],
            "rep_id": rep["rep_id"], "quote_date": quote_date.isoformat(),
            "quantity": qty, "quoted_price": price, "stage": stage,
            "approval_ref": approval_ref, "exception_reason_code": reason_code}


def maybe_book(rng, line, customer, booking_seq):
    """Convert a quote line to a booking, or leave it open or lost.

    Bookings are load-bearing here, not staged and forgotten. They are what
    split exposure into money already invoiced and money still in the funnel —
    which is the deal-desk argument stated in dollars.

    Every line gets an eventual outcome AND a date on which that outcome lands.
    If the decision date falls beyond the end of the window, the line is still
    OPEN as at the as-of date, whichever way it was going to go. Modelling it
    this way rather than "recent lines are probably open" is what makes open
    exposure a real, dated funnel rather than a fudge factor.
    """
    quote_date = date.fromisoformat(line["quote_date"])
    p_convert = CONVERSION_BY_SEGMENT[customer["segment"]]
    roll = rng.random()

    if roll < p_convert:
        lag = timedelta(days=int(rng.triangular(BOOKING_LAG_DAYS[0],
                                                BOOKING_LAG_DAYS[1],
                                                BOOKING_LAG_DAYS[0] + 15)))
        booking_date = quote_date + lag
        if booking_date > WINDOW_END:
            line["stage"] = "open"          # would have booked, hasn't yet
            return None
        line["stage"] = "won"
        booking_seq[0] += 1
        price = line["quoted_price"]
        if rng.random() < P_BOOKED_PRICE_DIFFERS:
            # The price moved between quote and order. Model it; never assume
            # booked_price == quoted_price.
            price = round(price * (1 + rng.gauss(0, BOOKED_PRICE_DRIFT)), 2)
        qty = line["quantity"]
        if rng.random() < P_PARTIAL_QUANTITY:
            qty = max(1, int(qty * rng.uniform(*PARTIAL_QUANTITY_RANGE)))
        return {"booking_id": f"BK-{booking_seq[0]:06d}", "quote_id": line["quote_id"],
                "line_no": line["line_no"], "customer_id": line["customer_id"],
                "product_id": line["product_id"],
                "booking_date": booking_date.isoformat(),
                "booked_quantity": qty, "booked_price": price}

    # Didn't convert — but a loss takes time to become a loss. If the customer
    # has not walked away yet as at the window end, the line is still open.
    decided_on = quote_date + timedelta(days=rng.randint(*LOSS_DECISION_LAG_DAYS))
    line["stage"] = "lost" if decided_on <= WINDOW_END else "open"
    return None


# ===========================================================================
# Assumptions document — written from the run, never by hand
# ===========================================================================

def write_assumptions(realized: dict) -> None:
    """governance/generator_assumptions.md, regenerated every run.

    The realized percentages are reported here whatever they are. If a run
    lands outside the design bands, the fix is the mechanism, not this number.
    """
    md = [
        "# Generator Assumptions — Cascadia Deal Desk",
        "",
        f"*Auto-generated by `src/generate.py`. Seed **{SEED}**, as-of "
        f"**{AS_OF.isoformat()}**, window **{WINDOW_START.isoformat()} → "
        f"{WINDOW_END.isoformat()}**.*",
        "",
        f"> **{DISCLOSURE}** There is no real pricing data in this project. Every "
        "customer, part number, price and person below was invented by this script "
        "from a fixed seed. Any resemblance to a real company, product or individual "
        "is unintended.",
        "",
        "## Why the variance is generated, not drawn",
        "",
        "The obvious way to build this dataset would be to draw the quoted price from",
        "a distribution around the agreed price. That produces directionless noise: an",
        "exception table with no story and a threshold control that does nothing when",
        "you drag it. So variance here comes from a **mechanism** instead.",
        "",
        "Every customer/product relationship carries a `prior_price` — what that",
        "customer paid before the current agreement. When an agreement is signed the",
        "`agreed_price` sits at a **premium** above it. An off-agreement line is a rep",
        "quoting the *prior* price: the old number, from habit or from a stale sheet.",
        "",
        "That one mechanism gives the analysis three properties for free:",
        "",
        "- variance is **negative** (undercharging), because the premium was positive;",
        "- variance is **larger where the premium was larger**, because it *is* the premium;",
        "- variance is **explainable**, because the counterfactual is a real column in the data.",
        "",
        "Jitter (a rounded number, a slightly stale sheet) sits on top, and is",
        "deliberately second-order. It is never the driver.",
        "",
        "## Realized mix (this run)",
        "",
        "| Outcome | Lines | Share of all lines | Design band |",
        "|---|---:|---:|---|",
    ]
    t = realized["total_lines"]
    md += [
        f"| Priced to agreement | {realized['priced_to_agreement']:,} | "
        f"{100 * realized['priced_to_agreement'] / t:.1f}% | 80–85% *of covered lines* |",
        f"| Priced off agreement | {realized['priced_off_agreement']:,} | "
        f"{100 * realized['priced_off_agreement'] / t:.1f}% | 13–16% of all lines |",
        f"| No governing agreement | {realized['no_governing_agreement']:,} | "
        f"{100 * realized['no_governing_agreement'] / t:.1f}% | 8–10% of all lines |",
        "",
        f"Of the **{realized['covered_lines']:,}** lines that have a governing agreement, "
        f"**{100 * realized['priced_to_agreement'] / realized['covered_lines']:.1f}%** are "
        "priced to it. A dataset where everything is broken is not credible and would "
        "undercut the argument.",
        "",
        f"Approved exceptions: **{realized['approved_exceptions']:,}** lines, "
        f"**{100 * realized['approved_exceptions'] / max(realized['priced_off_agreement'], 1):.1f}%** "
        "of off-agreement lines (design target ~12%). These are documented, approved "
        "deviations — without them there are no false positives to calibrate against "
        "and the threshold control on the exception page is theatre.",
        "",
        "## Parameter block",
        "",
        "Every tunable assumption in the dataset, as it was set for this run.",
        "",
        "| Parameter | Value | What it controls |",
        "|---|---|---|",
        f"| `SEED` | {SEED} | Fixed seed; the same seed reproduces byte-identical CSVs |",
        f"| `N_CUSTOMERS` / `N_PRODUCTS` / `N_REPS` | {N_CUSTOMERS} / {N_PRODUCTS} / {N_REPS} | Size of the book |",
        f"| `TARGET_QUOTE_LINES` | {TARGET_QUOTE_LINES:,} | Approximate line count (quotes carry 1–4 lines) |",
        f"| `TOLERANCE_PCT` | ±{TOLERANCE_PCT:.1%} | Band inside which a quote counts as priced *to* the agreement |",
        f"| `PREMIUM_NORMAL` / `PREMIUM_HARD` | {PREMIUM_NORMAL} / {PREMIUM_HARD} | The uplift a renegotiation won over `prior_price` |",
        f"| `PREMIUM_HARD_SHARE` | {PREMIUM_HARD_SHARE:.0%} | Share of agreements negotiated hard |",
        f"| `BASE_OFF_AGREEMENT_RATE` | {BASE_OFF_AGREEMENT_RATE} | Baseline P(off-agreement) before the three drivers |",
        f"| `REP_LEAK_STANDOUT` | {REP_LEAK_STANDOUT}× | The one rep who is the story |",
        f"| `N_LEAKY_REPS` | {N_LEAKY_REPS} of {N_REPS} | Reps carrying the clear majority of leakage |",
        f"| `RECENCY_PEAK_BOOST` / `RECENCY_DECAY_DAYS` | {RECENCY_PEAK_BOOST}× / {RECENCY_DECAY_DAYS:.0f}d | Leakage peaks just after a renegotiation, then decays |",
        f"| `N_HOT_CUSTOMERS` | {N_HOT_CUSTOMERS} | Accounts carrying most of the dollar exposure |",
        f"| `EXCEPTION_BASE_RATE` | {EXCEPTION_BASE_RATE} | Rate of documented, approved deviations |",
        f"| `P_EXCEPTION_POSITIVE` | {P_EXCEPTION_POSITIVE:.0%} | Approved deviations priced *above* agreement |",
        f"| `CHAIN_LENGTH_WEIGHTS` | {CHAIN_LENGTH_WEIGHTS} | How often a customer/part relationship renews |",
        f"| `SUCCESSOR_OVERLAP_P` | {SUCCESSOR_OVERLAP_P:.0%} | Successors back-dated into the predecessor's window |",
        f"| `N_UNLINKED_OVERLAPS` | {N_UNLINKED_OVERLAPS} | Duplicate registrations with no supersession link |",
        f"| `COST_DRIFT_MIX` (down/flat/up) | {COST_DRIFT_MIX} | Standard-cost trajectory per part |",
        f"| `CONVERSION_BY_SEGMENT` | {CONVERSION_BY_SEGMENT} | Quote → booking conversion |",
        f"| `YOY_GROWTH` | {YOY_GROWTH:.1%} | Year-2 quote volume vs year-1 |",
        "",
        "## Structures built on purpose",
        "",
        "A reader is entitled to know which findings were designed in rather than",
        "discovered. All of these are deliberate:",
        "",
        f"- **{N_HOT_CUSTOMERS} concentrated accounts** and **{N_LEAKY_REPS} undisciplined reps** "
        "(one standout), so the ranked-by-dollars charts have a genuine head and tail.",
        f"- **{N_MARGIN_EROSION_CUSTOMERS} margin-erosion accounts** — near-perfect compliance, "
        "but their parts carry *rising* standard cost. These produce the second, separate "
        "finding: the agreement was honoured and the margin still fell. That is a different "
        "failure from leakage and the data has to be able to tell them apart.",
        f"- **{N_EXCEPTION_ACCOUNTS} strategic accounts** where approved deviations cluster, "
        "some of them priced *above* the agreement.",
        f"- **{N_UNLINKED_OVERLAPS} duplicate registrations** with no supersession link — the "
        "case the recency tiebreak exists for.",
        f"- **{N_LATE_LAUNCH_PRODUCTS} parts that launch mid-window**, creating genuine "
        "`product_launched_after_agreement` coverage gaps.",
        "",
        "## No-agreement causes (this run)",
        "",
        "| Cause | Lines |",
        "|---|---:|",
    ]
    for cause, n in sorted(realized["no_agreement_reasons"].items(),
                           key=lambda kv: -kv[1]):
        md.append(f"| `{cause}` | {n:,} |")

    md += [
        "",
        "---",
        f"*{DISCLOSURE} Generated by `src/generate.py` at seed {SEED}. "
        "Independent portfolio project; illustrates a pricing-governance design "
        "on invented data only.*",
        "",
    ]
    ASSUMPTIONS_PATH.write_text("\n".join(md), encoding="utf-8")


# ===========================================================================
# Orchestration
# ===========================================================================

def main(out_dir: Path = RAW_DIR, quiet: bool = False) -> None:
    """Generate the whole dataset.

    `out_dir` is overridable so validate.py can regenerate into a temporary
    folder and prove the seed really is reproducible, without touching the
    committed artifact in data/raw/.
    """
    rng = random.Random(SEED)
    out_dir.mkdir(parents=True, exist_ok=True)
    ASSUMPTIONS_PATH.parent.mkdir(parents=True, exist_ok=True)

    reps = build_reps(rng)
    products = build_products(rng)
    customers = build_customers(rng, products)
    dates = build_dates()
    costs = build_standard_costs(rng, products)
    agreements = build_agreements(rng, customers, products)
    lines, bookings = build_quotes(rng, customers, products, reps, agreements)

    # --- realized mix, measured with the SAME matcher conform.py will use ---
    agreements_by_customer: dict = {}
    for a in agreements:
        agreements_by_customer.setdefault(a["customer_id"], []).append(a)
    agreement_by_id = {a["agreement_id"]: a for a in agreements}
    products_by_id = {p["product_id"]: p for p in products}

    from conform import no_agreement_reason
    tally = {"priced_to_agreement": 0, "priced_off_agreement": 0,
             "no_governing_agreement": 0}
    reasons: dict = {}
    for ln in lines:
        product = products_by_id[ln["product_id"]]
        qd = date.fromisoformat(ln["quote_date"])
        cust_ags = agreements_by_customer.get(ln["customer_id"], [])
        winner, _ = resolve_agreement(cust_ags, ln["product_id"], product["family"],
                                      qd, agreement_by_id)
        if winner is None:
            tally["no_governing_agreement"] += 1
            cause = no_agreement_reason(cust_ags, ln["product_id"], product["family"],
                                        qd, date.fromisoformat(product["launch_date"]))
            reasons[cause] = reasons.get(cause, 0) + 1
        elif abs(ln["quoted_price"] - winner["agreed_price"]) <= TOLERANCE_PCT * winner["agreed_price"]:
            tally["priced_to_agreement"] += 1
        else:
            tally["priced_off_agreement"] += 1

    realized = dict(tally)
    realized["total_lines"] = len(lines)
    realized["covered_lines"] = tally["priced_to_agreement"] + tally["priced_off_agreement"]
    realized["approved_exceptions"] = sum(1 for ln in lines if ln["approval_ref"])
    realized["no_agreement_reasons"] = reasons

    # --- write the raw layer ------------------------------------------------
    def public(rows, cols):
        """Drop the generator's private '_' columns; those are scaffolding."""
        return pd.DataFrame(rows)[cols]

    frames = {
        "dim_customer": public(customers, ["customer_id", "name", "segment", "region"]),
        "dim_product": public(products, ["product_id", "part_number", "family", "launch_date"]),
        "dim_rep": public(reps, ["rep_id", "name", "territory"]),
        "dim_date": pd.DataFrame(dates),
        "dim_agreement": public(agreements, [
            "agreement_id", "customer_id", "scope", "product_id", "family",
            "agreed_price", "effective_start", "effective_end", "committed_units",
            "approval_ref", "status", "superseded_by", "prior_price", "premium_pct"]),
        "fact_quote_line": public(lines, [
            "quote_id", "line_no", "customer_id", "product_id", "rep_id",
            "quote_date", "quantity", "quoted_price", "stage", "approval_ref",
            "exception_reason_code"]),
        "fact_booking": public(bookings, [
            "booking_id", "quote_id", "line_no", "customer_id", "product_id",
            "booking_date", "booked_quantity", "booked_price"]),
        "fact_standard_cost": pd.DataFrame(costs),
    }
    for name, df in frames.items():
        df.to_csv(out_dir / f"{name}.csv", index=False, lineterminator="\n")

    manifest = {
        "generator": "src/generate.py", "seed": SEED,
        "as_of": AS_OF.isoformat(),
        "window": {"start": WINDOW_START.isoformat(), "end": WINDOW_END.isoformat()},
        "disclosure": DISCLOSURE,
        "tolerance_pct": TOLERANCE_PCT,
        "row_counts": {n: int(len(df)) for n, df in frames.items()},
        "realized_mix": {k: v for k, v in realized.items() if k != "no_agreement_reasons"},
        "no_agreement_reasons": reasons,
    }
    (out_dir / "generator_manifest.json").write_text(json.dumps(manifest, indent=2),
                                                     encoding="utf-8")
    if quiet:                       # regeneration-for-verification run; leave the
        return                      # committed governance doc alone
    write_assumptions(realized)

    print(f"Wrote {len(frames)} CSVs to {out_dir}")
    for name, df in frames.items():
        print(f"  {name}: {len(df):,} rows")
    t = realized["total_lines"]
    print("Realized mix:")
    for k in ("priced_to_agreement", "priced_off_agreement", "no_governing_agreement"):
        print(f"  {k}: {realized[k]:,} ({100 * realized[k] / t:.1f}%)")
    print(f"  priced_to_agreement as share of COVERED lines: "
          f"{100 * realized['priced_to_agreement'] / realized['covered_lines']:.1f}%")
    print(f"  approved exceptions: {realized['approved_exceptions']:,} "
          f"({100 * realized['approved_exceptions'] / max(realized['priced_off_agreement'], 1):.1f}% "
          f"of off-agreement)")
    print(f"  no-agreement causes: {reasons}")
    print(f"Wrote {ASSUMPTIONS_PATH}")


if __name__ == "__main__":
    main()
